### ISSUE TITLE
UDP

### ISSUE THREAD

**Issue by Taherismail17** [itsjohnye/Lead-iOS-Demo#1]
Hi,

The app does not work with UDP so apps like Youtube will not work when connected to the Proxy.

**Comment by itsjohnye** [comment]
> Hi,
> 
> The app does not work with UDP so apps like Youtube will not work when connected to the Proxy.
@Taherismail17 


Thanks for reporting the issue.
But mine is working properly.

So please double check it if it's necessary:
1. make sure it's running on a real iOS device not on a simulator.
2. your proxy setting is correct.
3. you can set your own rules in NEKitRule.conf.

**Comment by Taherismail17** [comment]
Since enable packet tunnel processing is disabled UDP does not get sent through the tunnel. UDP works with Potatso, Shadowrocket etc.
